[build]
  publish = "public"
  command = "echo 'No build required'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/play/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/artist/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/album/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/playlist/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
